image: node:slim

# Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm/
stages:
    - test
    - build
    - deploy

before_script:
    - npm ci --cache .npm --prefer-offline
    - npm i -g firebase-tools

build:
    stage: build
    script: npm run build:prod

test:
    stage: test
    script: npm run lint

deploy:
    stage: deploy
    script: firebase deploy --token $FIREBASE_TOKEN



