image: node:latest

# Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm/

before_script:
    - npm ci --cache .npm --prefer-offline

stages:
    - build
    - test

build:
    stage: build
    script: npm run build

test:
    stage: test
    script: npm run lint:es && npm test
