image: node:slim

# Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/


before_script:
    - npm install

build:
    script: npm run build

test:
    script: npm run lint:es && npm test


