image: node:slim

# Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm/


before_script:
    - npm ci --cache .npm --prefer-offline

build:
    script: npm run build

test:
    script: npm run lint:es && npm test


